### ISSUE TITLE
Return as object instead of an array

### ISSUE THREAD

**Issue by dylang** [hemanth/get-hosts#3]
I'm wondering if it would make more sense to return as an object, such as
`"hostname": "127.0.0.1"`, this might make searching and organizing easier. 

This assumes that hostnames each only have one ip address assigned to them, even if they are in the `hosts` file more than once.

**Comment by hemanth** [comment]
I had the same thought!

**Comment by captn3m0** [comment]
Was going to file a PR for this, but it seems you are already on it :)

**Comment by hemanth** [comment]
@captn3m0 PR for fixing #1 is welcomed, I have cooked a quick version of it at [next](https://github.com/hemanth/get-hosts/tree/next).

P.S: Sorry for the delay, /me was on a road trip ;)

**Comment by hemanth** [comment]
Fixed in `v2.0.0`
